---
- name: 'Install Satellite/Capsule software and prepare the system'
  hosts: 'all'
  gather_facts: true
  become: true

  tasks:
    - name: 'Handle fapolicyd setup'
      when: >
        sat_fapolicyd_enabled is defined
        and sat_fapolicyd_enabled
      block:

        - name: 'Install and configure fapolicyd via system role'
          ansible.builtin.include_role:
            name: 'redhat.rhel_system_roles.fapolicyd'

        - name: 'Deploy custom fapolicyd rules'
          ansible.builtin.copy:
            content: |
              {% for rule in _t_rule.rules %}
              {{ rule }}
              {% endfor %}
            dest: '/etc/fapolicyd/rules.d/{{ _t_rule.name }}.rules'
            owner: 'root'
            group: 'fapolicyd'
            mode: '0644'
          loop: '{{ sat_fapolicyd_rules }}'
          loop_control:
            loop_var: '_t_rule'
            label: '{{ _t_rule.name }}'
          when: >
            sat_fapolicyd_rules is defined
            and sat_fapolicyd_rules | length > 0
          notify: '_restart_fapolicyd'

    - name: 'Update all packages'
      ansible.builtin.dnf:
        name: '*'
        state: 'latest'
        update_only: true
      register: '_t_update'

    - name: 'Install {{ sat_package_name }} package'
      ansible.builtin.dnf:
        name: '{{ sat_package_name }}'
        update_cache: true

    - name: 'Reboot the server'
      ansible.builtin.reboot:
        reboot_timeout: 3600
      when: >
        _t_update.changed is defined
        and _t_update.changed

  handlers:
    - name: 'Restart fapolicyd'
      listen: '_restart_fapolicyd'
      ansible.builtin.service:
        name: 'fapolicyd'
        state: 'restarted'
