---
- name: 'Configure OpenSCAP on a Red Hat Satellite'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Handle enabling of OpenSCAP Ansible role'
      when: >
        sat_scap_enable_foreman_ansible_role is defined
        and sat_scap_enable_foreman_ansible_role
      block:

        - name: 'Retrieve ID of {{ inventory_hostname }}'
          redhat.satellite.resource_info:
            username: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            server_url: '{{ satellite_server_url }}'
            validate_certs: '{{ satellite_validate_certs }}'
            resource: 'capsules'
            search: 'name = {{ inventory_hostname }}'
          register: '__t_capsules'

        - name: 'Ensure only one result is returned'
          ansible.builtin.assert:
            that:
              - __t_capsules.resources is defined
              - __t_capsules.resources is not string
              - __t_capsules.resources is not mapping
              - __t_capsules.resources is iterable
              - __t_capsules.resources | length == 1
              - __t_capsules.resources[0].id is defined
              - __t_capsules.resources[0].id is number
              - __t_capsules.resources[0].id | string | int == __t_capsules.resources[0].id | int

        - name: 'Enable Foreman OpenSCAP Ansible role: {{ sat_scap_foreman_role_name }}'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/ansible/api/ansible_roles/sync'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'PUT'
            body: |
              {{
                {
                  'proxy_id': __t_capsules.resources[0].id,
                  'role_names': [
                    sat_scap_foreman_role_name
                  ]
                }

              }}
            force_basic_auth: true
            body_format: 'json'

        - name: 'Ensure OpenSCAP role is available in Satellite'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/ansible/api/ansible_roles'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            body: |
              {{
                {
                  'search': 'name = ' ~ sat_scap_foreman_role_name
                }
              }}
            force_basic_auth: true
            body_format: 'json'
          register: '__t_roles'
          until: __t_roles.json.results | selectattr('name', 'match', sat_scap_foreman_role_name) | length == 1


    - name: 'Enable default OpenSCAP content provided by Satellite'
      ansible.builtin.uri:
        url: '{{ satellite_server_url }}/api/v2/compliance/scap_contents/bulk_upload'
        user: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: '{{ satellite_validate_certs }}'
        method: 'POST'
        body: |
          {{
            {
              'type': 'default'
            }
          }}
        force_basic_auth: true
        body_format: 'json'
      delegate_to: 'localhost'
      when: >
        sat_scap_enable_default_content is defined
        and sat_scap_enable_default_content


    - name: 'Handle creation of OpenSCAP compliance policies'
      when: >
        sat_scap_compliance_policies is defined
        and sat_scap_compliance_policies | length > 0
      block:

        - name: 'Retrieve available SCAP contents'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/compliance/scap_contents?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_scap_contents'

        - name: 'Retrieve available SCAP content profiles'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/compliance/scap_content_profiles?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_scap_profiles'

        - name: 'Build SCAP content title to ID lookup'
          ansible.builtin.set_fact:
            __t_scap_content_ids: >-
              {{
                dict(
                  __t_scap_contents.json.results | map(attribute='title')
                  | zip(__t_scap_contents.json.results | map(attribute='id'))
                )
              }}

        - name: 'Build SCAP content profile lookup: {{ __t_profile.scap_content.title }} -> {{ __t_profile.profile_id }}'
          ansible.builtin.set_fact:
            __t_scap_profile_ids: >-
              {{
                __t_scap_profile_ids | default({})
                | combine({
                  __t_profile.scap_content.title ~ '::' ~ __t_profile.profile_id: __t_profile.id
                })
              }}
          loop: '{{ __t_scap_profiles.json.results }}'
          loop_control:
            loop_var: '__t_profile'
            label: '{{ __t_profile.scap_content.title ~ " -> " ~ __t_profile.profile_id }}'

        - name: 'Retrieve organizations'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/organizations?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_organizations'

        - name: 'Retrieve locations'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/locations?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_locations'

        - name: 'Retrieve hostgroups'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/hostgroups?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_hostgroups'

        - name: 'Build name-to-ID lookups'
          ansible.builtin.set_fact:
            __t_org_ids: >-
              {{
                dict(
                  __t_organizations.json.results | map(attribute='name')
                  | zip(__t_organizations.json.results | map(attribute='id'))
                )
              }}
            __t_loc_ids: >-
              {{
                dict(
                  __t_locations.json.results | map(attribute='name')
                  | zip(__t_locations.json.results | map(attribute='id'))
                )
              }}
            __t_hg_ids: >-
              {{
                dict(
                  __t_hostgroups.json.results | map(attribute='title')
                  | zip(__t_hostgroups.json.results | map(attribute='id'))
                )
              }}

        - name: 'Retrieve existing compliance policies'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/compliance/policies?per_page=1000'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            force_basic_auth: true
            body_format: 'json'
          delegate_to: 'localhost'
          register: '__t_existing_policies'

        - name: 'Create compliance policy: {{ __t_policy.name }}'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/api/v2/compliance/policies'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'POST'
            body: |
              {{
                {
                  'policy':
                    {
                      'name': __t_policy.name,
                      'description': __t_policy.description | default(''),
                      'scap_content_id': __t_scap_content_ids[__t_policy.scap_content],
                      'scap_content_profile_id': __t_scap_profile_ids[__t_policy.scap_content ~ '::' ~ __t_policy.scap_content_profile],
                      'period': __t_policy.period,
                      'deploy_by': __t_policy.deploy_by,
                      'organization_ids': __t_policy.organizations | map('extract', __t_org_ids) | list,
                      'location_ids': __t_policy.locations | map('extract', __t_loc_ids) | list,
                      'hostgroup_ids': __t_policy.hostgroups | map('extract', __t_hg_ids) | list
                    }
                    | combine(
                      {'weekday': __t_policy.weekday}
                      if __t_policy.period == 'weekly' and __t_policy.weekday is defined
                      else {}
                    )
                    | combine(
                      {'day_of_month': __t_policy.day_of_month}
                      if __t_policy.period == 'monthly' and __t_policy.day_of_month is defined
                      else {}
                    )
                    | combine(
                      {'cron_line': __t_policy.cron_line}
                      if __t_policy.period == 'custom' and __t_policy.cron_line is defined
                      else {}
                    )
                }

              }}
            force_basic_auth: true
            body_format: 'json'
            status_code: 201
          changed_when: true
          delegate_to: 'localhost'
          when: >
            __t_existing_policies.json.results
            | selectattr('name', 'equalto', __t_policy.name)
            | length == 0
          loop: '{{ sat_scap_compliance_policies }}'
          loop_control:
            loop_var: '__t_policy'
            label: '{{ __t_policy.name }}'
