---
- name: 'Configure OpenSCAP on a Red Hat Satellite'
  hosts: 'all'
  gather_facts: false
  tasks:
    - name: 'Handle enabling of OpenSCAP Ansible role'
      when: >
        sat_scap_enable_foreman_ansible_role is defined
        and sat_scap_enable_foreman_ansible_role
      block:

        - name: 'Retrieve ID of {{ inventory_hostname }}'
          redhat.satellite.resource_info:
            username: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            server_url: '{{ satellite_server_url }}'
            validate_certs: '{{ satellite_validate_certs }}'
            resource: 'capsules'
            search: 'name = {{ inventory_hostname }}'
          register: '__t_capsules'

        - name: 'Ensure only one result is returned'
          ansible.builtin.assert:
            that:
              - __t_capsules.resources is defined
              - __t_capsules.resources is not string
              - __t_capsules.resources is not mapping
              - __t_capsules.resources is iterable
              - __t_capsules.resources | length == 1
              - __t_capsules.resources[0].id is defined
              - __t_capsules.resources[0].id is number
              - __t_capsules.resources[0].id | string | int == __t_capsules.resources[0].id | int

        - name: 'Enable Foreman OpenSCAP Ansible role: {{ sat_scap_foreman_role_name }}'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/ansible/api/ansible_roles/sync'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'PUT'
            body: |
              {{
                {
                  'proxy_id': __t_capsules.resources[0].id,
                  'role_names': [
                    sat_scap_foreman_role_name
                  ]
                }

              }}
            force_basic_auth: true
            body_format: 'json'

        - name: 'Ensure OpenSCAP role is available in Satellite'
          ansible.builtin.uri:
            url: '{{ satellite_server_url }}/ansible/api/ansible_roles'
            user: '{{ satellite_username }}'
            password: '{{ satellite_password }}'
            validate_certs: '{{ satellite_validate_certs }}'
            method: 'GET'
            body: |
              {{
                {
                  'search': 'name = ' ~ sat_scap_foreman_role_name
                }
              }}
            force_basic_auth: true
            body_format: 'json'
          register: '__t_roles'
          until: __t_roles.json.results | selectattr('name', 'match', sat_scap_foreman_role_name) | length == 1


    - name: 'Enable default OpenSCAP content provided by Satellite'
      ansible.builtin.uri:
        url: '{{ satellite_server_url }}/api/v2/compliance/scap_contents/bulk_upload'
        user: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        validate_certs: '{{ satellite_validate_certs }}'
        method: 'POST'
        body: |
          {{
            {
              'type': 'default'
            }
          }}
        force_basic_auth: true
        body_format: 'json'
      delegate_to: 'localhost'
      when: >
        sat_scap_enable_default_content is defined
        and sat_scap_enable_default_content


    - name: 'Manage OpenSCAP compliance policies'
      scap_policy:
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        server_url: '{{ satellite_server_url }}'
        validate_certs: '{{ satellite_validate_certs }}'
        name: '{{ __t_policy.name }}'
        description: '{{ __t_policy.description | default(omit) }}'
        scap_content: '{{ __t_policy.scap_content }}'
        scap_content_profile: '{{ __t_policy.scap_content_profile }}'
        deploy_by: '{{ __t_policy.deploy_by }}'
        period: '{{ __t_policy.period }}'
        weekday: '{{ __t_policy.weekday | default(omit) }}'
        day_of_month: '{{ __t_policy.day_of_month | default(omit) }}'
        cron_line: '{{ __t_policy.cron_line | default(omit) }}'
        organizations: '{{ __t_policy.organizations }}'
        locations: '{{ __t_policy.locations }}'
        hostgroups: '{{ __t_policy.hostgroups | default([]) }}'
        state: '{{ __t_policy.state | default("present") }}'
      delegate_to: 'localhost'
      when: >
        sat_scap_compliance_policies is defined
        and sat_scap_compliance_policies | length > 0
      loop: '{{ sat_scap_compliance_policies }}'
      loop_control:
        loop_var: '__t_policy'
        label: '{{ __t_policy.name }}'
