---
- name: 'Configure users in Red Hat Satellite'
  hosts: 'all'
  gather_facts: false

  tasks:
    - name: 'Configure Users'
      redhat.satellite.user:
        username: '{{ satellite_username }}'
        password: '{{ satellite_password }}'
        server_url: '{{ satellite_server_url }}'
        validate_certs: '{{ satellite_validate_certs }}'
        name: '{{ __t_user.name }}'
        firstname: '{{ __t_user.firstname | default(omit) }}'
        lastname: '{{ __t_user.lastname | default(omit) }}'
        mail: '{{ __t_user.mail }}'
        auth_source: '{{ __t_user.auth_source | default("Internal") }}'
        user_password: '{{ __t_user.password | default(omit) }}'
        admin: '{{ __t_user.admin | default(false) }}'
        roles: '{{ __t_user.roles | default(omit) }}'
        locations: '{{ __t_user.locations | default(omit) }}'
        organizations: '{{ __t_user.organizations | default(omit) }}'
        state: '{{ __t_user.state | default("present") }}'
      loop: '{{ sat_users }}'
      loop_control:
        loop_var: '__t_user'
        label: '{{ __t_user.name }}'
...