---
- name: 'Full Satellite Deployment'
  hosts: 'all'
  gather_facts: false

  tasks:
    - name: 'Phase: Registration and Installation'
      ansible.builtin.debug:
        msg: 'Starting Satellite deployment for {{ inventory_hostname }}'

- name: 'Register Satellite host with Red Hat'
  ansible.builtin.import_playbook: '01_register_satellite.yml'

- name: 'Install Red Hat Satellite'
  ansible.builtin.import_playbook: '02_satellite_installer.yml'

- name: 'Download and upload subscription manifest'
  ansible.builtin.import_playbook: '04_satellite_manifest.yml'

- name: 'Create content credentials'
  ansible.builtin.import_playbook: '05_satellite_content_credentials.yml'

- name: 'Enable products and repositories'
  ansible.builtin.import_playbook: '06_satellite_products_and_repositories.yml'

- name: 'Synchronize repositories'
  ansible.builtin.import_playbook: '07_satellite_sync_repositories.yml'

- name: 'Create sync plans'
  ansible.builtin.import_playbook: '08_satellite_sync_plans.yml'

- name: 'Create lifecycle environments'
  ansible.builtin.import_playbook: '09_satellite_lifecycle_environments.yml'

- name: 'Create domains'
  ansible.builtin.import_playbook: '10_satellite_domains.yml'

- name: 'Create subnets'
  ansible.builtin.import_playbook: '11_satellite_subnets.yml'

- name: 'Create content views'
  ansible.builtin.import_playbook: '12_satellite_content_views.yml'

- name: 'Publish and promote content views'
  ansible.builtin.import_playbook: '13_satellite_content_view_publish.yml'

- name: 'Apply Satellite settings'
  ansible.builtin.import_playbook: '14_satellite_settings.yml'

- name: 'Configure operating systems'
  ansible.builtin.import_playbook: '16_satellite_operating_systems.yml'

- name: 'Create activation keys'
  ansible.builtin.import_playbook: '17_satellite_activation_keys.yml'

- name: 'Create host groups'
  ansible.builtin.import_playbook: '18_satellite_host_groups.yml'

- name: 'Set global parameters'
  ansible.builtin.import_playbook: '19_satellite_global_parameters.yml'

- name: 'Configure OpenSCAP'
  ansible.builtin.import_playbook: '20_satellite_openscap.yml'

- name: 'Create Satellite roles'
  ansible.builtin.import_playbook: '21_satellite_role.yml'

- name: 'Create Satellite users'
  ansible.builtin.import_playbook: '22_satellite_users.yml'
