download_url: https://console.redhat.com/api/automation-hub/v3/plugin/ansible/content/published/collections/artifacts/redhat-satellite-5.7.0.tar.gz
format_version: 1.0.0
name: satellite
namespace: redhat
server: https://console.redhat.com/api/automation-hub/
signatures:
- pubkey_fingerprint: 39B5D759361A97464C564A8FE1A4BD708A828AAD
  pulp_created: '2025-10-14T11:06:49.976819Z'
  signature: '-----BEGIN PGP SIGNATURE-----


    iQIcBAABCAAGBQJo7i6/AAoJEOGkvXCKgoqt2sYQAJOH9iQwfDlQdlE8sfo/wN6w

    WlVaKZjyTBNoofjCKVGJxFocykfPgwe1w054B3MktwhGfdj529Z6SuL5I1TAUeM5

    bbocn+Z75Jdar14u+NxJR0zmeRWJ7DfaQj6uB/yuwNHlKVFTheGJsQrgA5998d8d

    RLYDOHh2ZpEvgbcOsHP8O7XHyGIcqqon5TMpPTFl2vdRfQq7ZELlIF1qgP3RMHlp

    3oWDnL+NjGp9V1wgk4VQJj4JTyII1KM2yn55G4yL2imQCEOeqgi1lZHQm/blUk/B

    SKzZMJQzgAVWcBu9jSjC7RWTAXaSP2pP+FIJt/6xWezWqeFzDN9R3NhmtXzASfcp

    qfmjJWxWXa2gfJNwbVDxM9Erfjh5eY6p3UDVj5U3TfcvCgcU4fdGjyNecHEreU5g

    Th1Bg49V8eRClaI5K0/vXNvw7a0rPt42Bs6PpCEbVq46puH0u7pdwBInlsJygfEQ

    48PtmKe03aJ8tI6+MERX0VBkPaHI/0SJeH2yHbR3c/aIbp/iYD82dVvlsbJAvAHF

    ouC5Hos+CN+etc/IVZxWY6E00D4OXfH8HtOd2oZq5kuDlVTRKwVynNG8gRE36Qhi

    FlEcbuzKBxWxR/xsZV+ClFOzYpJ8KXeq4xQmFtEkUEB+vSgVDTe+8o/i43KjSmSq

    mCtg+/acjG5Ar3huauhh

    =iM9g

    -----END PGP SIGNATURE-----

    '
  signing_service: null
version: 5.7.0
version_url: /api/automation-hub/v3/plugin/ansible/content/published/collections/index/redhat/satellite/versions/5.7.0/
